"""Unit tests for the OGC discovery walker (respx-mocked HTTP)."""

from __future__ import annotations

from typing import TYPE_CHECKING

import pytest
import respx
from httpx import Response

from gisweep.core.http import HttpClient
from gisweep.core.options import ScanOptions
from gisweep.discovery.ogc_enum import OgcEnumerator, _fingerprint

if TYPE_CHECKING:
    from collections.abc import AsyncIterator


BASE = "https://gs.example/geoserver"

_WMS_BODY = """<?xml version="1.0" encoding="UTF-8"?>
<WMS_Capabilities version="1.3.0"
  xmlns="http://www.opengis.net/wms"
  xmlns:xlink="http://www.w3.org/1999/xlink">
  <Service><Name>GeoServer 2.24.1</Name><Title>Demo</Title></Service>
  <Capability>
    <Request>
      <GetCapabilities><Format>application/xml</Format></GetCapabilities>
      <GetMap><Format>image/png</Format></GetMap>
      <GetFeatureInfo><Format>text/html</Format></GetFeatureInfo>
    </Request>
    <Layer queryable="1">
      <Name>citizen:addresses</Name>
      <Title>Citizen address points</Title>
    </Layer>
  </Capability>
</WMS_Capabilities>
"""

_WFS_BODY_WITH_TX = """<?xml version="1.0" encoding="UTF-8"?>
<wfs:WFS_Capabilities version="2.0.0"
  xmlns:wfs="http://www.opengis.net/wfs/2.0"
  xmlns:ows="http://www.opengis.net/ows/1.1">
  <ows:ServiceIdentification><ows:Title>GeoServer 2.20.4 WFS</ows:Title></ows:ServiceIdentification>
  <ows:OperationsMetadata>
    <ows:Operation name="GetCapabilities"/>
    <ows:Operation name="GetFeature"/>
    <ows:Operation name="Transaction"/>
    <ows:Operation name="LockFeature"/>
  </ows:OperationsMetadata>
  <wfs:FeatureTypeList>
    <wfs:FeatureType><wfs:Name>citizen:people</wfs:Name></wfs:FeatureType>
  </wfs:FeatureTypeList>
</wfs:WFS_Capabilities>
"""


@pytest.fixture
async def http() -> AsyncIterator[HttpClient]:
    client = HttpClient(ScanOptions())
    yield client
    await client.aclose()


def test_fingerprint_geoserver_with_version() -> None:
    fp = _fingerprint("Powered by GeoServer 2.24.1 deployment")
    assert fp.software == "geoserver"
    assert fp.version == "2.24.1"


def test_fingerprint_mapserver() -> None:
    fp = _fingerprint("Generated by MapServer 7.6.4 on Linux")
    assert fp.software == "mapserver"
    assert fp.version == "7.6.4"


def test_fingerprint_qgis() -> None:
    fp = _fingerprint("<Service>QGIS Server 3.22.0</Service>")
    assert fp.software == "qgis_server"
    assert fp.version == "3.22.0"


def test_fingerprint_unknown() -> None:
    fp = _fingerprint("<Capabilities>some random server</Capabilities>")
    assert fp.software == "unknown"
    assert fp.version is None


@respx.mock
async def test_probe_yields_wms_capabilities(http: HttpClient) -> None:
    respx.get(url__regex=rf"{BASE}/wms\?.*").mock(
        return_value=Response(
            200,
            text=_WMS_BODY,
            headers={"Content-Type": "application/vnd.ogc.wms_xml"},
        )
    )
    respx.get(url__regex=rf"{BASE}/wfs\?.*").mock(return_value=Response(404))
    respx.get(url__regex=rf"{BASE}/.*").mock(return_value=Response(404))
    respx.get(url__regex=r"https://gs\.example/.*").mock(return_value=Response(404))

    enumerator = OgcEnumerator(http, BASE)
    results = [cap async for cap in enumerator.probe(paths=["wms"])]

    assert len(results) == 1
    cap = results[0]
    assert cap.service == "WMS"
    assert cap.version == "1.3.0"
    assert cap.fingerprint.software == "geoserver"
    assert cap.fingerprint.version == "2.24.1"
    assert any(layer.name == "citizen:addresses" for layer in cap.layers)
    assert "GetCapabilities" in cap.operations
    assert "GetMap" in cap.operations


@respx.mock
async def test_probe_yields_wfs_with_transaction(http: HttpClient) -> None:
    respx.get(url__regex=rf"{BASE}/wfs\?.*").mock(
        return_value=Response(
            200,
            text=_WFS_BODY_WITH_TX,
            headers={"Content-Type": "application/xml"},
        )
    )
    respx.get(url__regex=rf"{BASE}\?.*").mock(return_value=Response(404))

    enumerator = OgcEnumerator(http, BASE)
    results = [cap async for cap in enumerator.probe(paths=["wfs"])]
    wfs = next((cap for cap in results if cap.service == "WFS"), None)
    assert wfs is not None
    assert wfs.version == "2.0.0"
    assert "Transaction" in wfs.operations
    assert "LockFeature" in wfs.operations


@respx.mock
async def test_probe_skips_non_xml_responses(http: HttpClient) -> None:
    respx.get(url__regex=r"https://gs\.example/.*").mock(
        return_value=Response(
            200, text="<html>not xml</html>", headers={"Content-Type": "text/html"}
        )
    )
    enumerator = OgcEnumerator(http, BASE)
    results = [cap async for cap in enumerator.probe(paths=["wms"])]
    assert results == []
